apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::562029726794:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::562029726794:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-PA889OOJBT5B
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-15T17:06:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1402"
  uid: 864709ba-ea21-45d1-b6e9-0524e59570a9
